"""first migration

Revision ID: 46044966b02e
Revises: 
Create Date: 2023-04-23 02:51:50.865713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46044966b02e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guchi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guchi')
    # ### end Alembic commands ###
