[phases.setup]
nixPkgs = ['python38','postgresql','gcc']

[phases.build]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt','cd db','alembic upgrade head']

[start]
cmd = 'uvicorn app.main:app --reload'