[phases.setup]
nixPkgs = ['python38','postgresql','gcc']

[phases.build]
cmds = ['cd db && alembic upgrade head','apt-get update -y','mkcert localhost']

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port=80 --ssl-keyfile localhost-key.pem --ssl-certfile localhost.pem'